// Comprehensive language registry for normalization and validation.
// Maps ISO 639-1/639-3 codes to display metadata, plus aliases for common names.

export interface LanguageEntry {
  code: string;
  name: string;
  nativeName: string;
  family?: string;
}

/**
 * Registry of supported language codes with display metadata.
 * Covers ISO 639-1 codes and select ISO 639-3 codes for languages
 * commonly found in language-learning resources.
 */
export const LANGUAGE_REGISTRY: Record<string, LanguageEntry> = {
  af: { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', family: 'Germanic' },
  am: { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', family: 'Semitic' },
  ar: { code: 'ar', name: 'Arabic', nativeName: 'العربية', family: 'Semitic' },
  hy: { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', family: 'Armenian' },
  az: { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', family: 'Turkic' },
  eu: { code: 'eu', name: 'Basque', nativeName: 'Euskara', family: 'Isolate' },
  be: { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', family: 'Slavic' },
  bn: { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', family: 'Indo-Aryan' },
  bs: { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', family: 'Slavic' },
  bg: { code: 'bg', name: 'Bulgarian', nativeName: 'Български', family: 'Slavic' },
  my: { code: 'my', name: 'Burmese', nativeName: 'မြန်မာ', family: 'Sino-Tibetan' },
  ca: { code: 'ca', name: 'Catalan', nativeName: 'Català', family: 'Romance' },
  zh: { code: 'zh', name: 'Chinese', nativeName: '中文', family: 'Sinitic' },
  yue: { code: 'yue', name: 'Cantonese', nativeName: '粵語', family: 'Sinitic' },
  hr: { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', family: 'Slavic' },
  cs: { code: 'cs', name: 'Czech', nativeName: 'Čeština', family: 'Slavic' },
  da: { code: 'da', name: 'Danish', nativeName: 'Dansk', family: 'Germanic' },
  nl: { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', family: 'Germanic' },
  en: { code: 'en', name: 'English', nativeName: 'English', family: 'Germanic' },
  et: { code: 'et', name: 'Estonian', nativeName: 'Eesti', family: 'Uralic' },
  fi: { code: 'fi', name: 'Finnish', nativeName: 'Suomi', family: 'Uralic' },
  fr: { code: 'fr', name: 'French', nativeName: 'Français', family: 'Romance' },
  ff: { code: 'ff', name: 'Fula', nativeName: 'Fulfulde', family: 'Atlantic' },
  ka: { code: 'ka', name: 'Georgian', nativeName: 'ქართული', family: 'Kartvelian' },
  de: { code: 'de', name: 'German', nativeName: 'Deutsch', family: 'Germanic' },
  el: { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', family: 'Hellenic' },
  gu: { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', family: 'Indo-Aryan' },
  ha: { code: 'ha', name: 'Hausa', nativeName: 'Hausa', family: 'Chadic' },
  he: { code: 'he', name: 'Hebrew', nativeName: 'עברית', family: 'Semitic' },
  hi: { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', family: 'Indo-Aryan' },
  hu: { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', family: 'Uralic' },
  is: { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', family: 'Germanic' },
  ig: { code: 'ig', name: 'Igbo', nativeName: 'Igbo', family: 'Niger-Congo' },
  id: { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', family: 'Austronesian' },
  ga: { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', family: 'Celtic' },
  it: { code: 'it', name: 'Italian', nativeName: 'Italiano', family: 'Romance' },
  ja: { code: 'ja', name: 'Japanese', nativeName: '日本語', family: 'Japonic' },
  jv: { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa', family: 'Austronesian' },
  kn: { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', family: 'Dravidian' },
  kk: { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі', family: 'Turkic' },
  km: { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', family: 'Austroasiatic' },
  rn: { code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi', family: 'Bantu' },
  kg: { code: 'kg', name: 'Kongo', nativeName: 'Kikongo', family: 'Bantu' },
  ko: { code: 'ko', name: 'Korean', nativeName: '한국어', family: 'Koreanic' },
  ku: { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî', family: 'Iranian' },
  ky: { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча', family: 'Turkic' },
  lo: { code: 'lo', name: 'Lao', nativeName: 'ລາວ', family: 'Kra-Dai' },
  la: { code: 'la', name: 'Latin', nativeName: 'Latina', family: 'Italic' },
  lv: { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', family: 'Baltic' },
  ln: { code: 'ln', name: 'Lingala', nativeName: 'Lingála', family: 'Bantu' },
  lt: { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', family: 'Baltic' },
  lg: { code: 'lg', name: 'Luganda', nativeName: 'Luganda', family: 'Bantu' },
  lb: { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', family: 'Germanic' },
  mk: { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', family: 'Slavic' },
  mg: { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy', family: 'Austronesian' },
  ms: { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', family: 'Austronesian' },
  ml: { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', family: 'Dravidian' },
  mt: { code: 'mt', name: 'Maltese', nativeName: 'Malti', family: 'Semitic' },
  mi: { code: 'mi', name: 'Māori', nativeName: 'Te Reo Māori', family: 'Austronesian' },
  mr: { code: 'mr', name: 'Marathi', nativeName: 'मराठी', family: 'Indo-Aryan' },
  mn: { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', family: 'Mongolic' },
  ne: { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', family: 'Indo-Aryan' },
  no: { code: 'no', name: 'Norwegian', nativeName: 'Norsk', family: 'Germanic' },
  nb: { code: 'nb', name: 'Norwegian Bokmål', nativeName: 'Norsk Bokmål', family: 'Germanic' },
  nn: { code: 'nn', name: 'Norwegian Nynorsk', nativeName: 'Norsk Nynorsk', family: 'Germanic' },
  ny: { code: 'ny', name: 'Chichewa', nativeName: 'Chinyanja', family: 'Bantu' },
  ps: { code: 'ps', name: 'Pashto', nativeName: 'پښتو', family: 'Iranian' },
  fa: { code: 'fa', name: 'Persian', nativeName: 'فارسی', family: 'Iranian' },
  pl: { code: 'pl', name: 'Polish', nativeName: 'Polski', family: 'Slavic' },
  pt: { code: 'pt', name: 'Portuguese', nativeName: 'Português', family: 'Romance' },
  pa: { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', family: 'Indo-Aryan' },
  ro: { code: 'ro', name: 'Romanian', nativeName: 'Română', family: 'Romance' },
  ru: { code: 'ru', name: 'Russian', nativeName: 'Русский', family: 'Slavic' },
  sm: { code: 'sm', name: 'Samoan', nativeName: 'Gagana Samoa', family: 'Austronesian' },
  gd: { code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig', family: 'Celtic' },
  sr: { code: 'sr', name: 'Serbian', nativeName: 'Српски', family: 'Slavic' },
  sh: { code: 'sh', name: 'Serbo-Croatian', nativeName: 'Srpskohrvatski', family: 'Slavic' },
  sn: { code: 'sn', name: 'Shona', nativeName: 'ChiShona', family: 'Bantu' },
  si: { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', family: 'Indo-Aryan' },
  sk: { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', family: 'Slavic' },
  sl: { code: 'sl', name: 'Slovene', nativeName: 'Slovenščina', family: 'Slavic' },
  so: { code: 'so', name: 'Somali', nativeName: 'Soomaali', family: 'Cushitic' },
  es: { code: 'es', name: 'Spanish', nativeName: 'Español', family: 'Romance' },
  sw: { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', family: 'Bantu' },
  sv: { code: 'sv', name: 'Swedish', nativeName: 'Svenska', family: 'Germanic' },
  tl: { code: 'tl', name: 'Tagalog', nativeName: 'Tagalog', family: 'Austronesian' },
  ta: { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', family: 'Dravidian' },
  te: { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', family: 'Dravidian' },
  th: { code: 'th', name: 'Thai', nativeName: 'ไทย', family: 'Kra-Dai' },
  ti: { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ', family: 'Semitic' },
  tr: { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', family: 'Turkic' },
  tk: { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen', family: 'Turkic' },
  tw: { code: 'tw', name: 'Twi', nativeName: 'Twi', family: 'Kwa' },
  uk: { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', family: 'Slavic' },
  ur: { code: 'ur', name: 'Urdu', nativeName: 'اردو', family: 'Indo-Aryan' },
  uz: { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbekcha', family: 'Turkic' },
  vi: { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', family: 'Austroasiatic' },
  cy: { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', family: 'Celtic' },
  xh: { code: 'xh', name: 'Xhosa', nativeName: 'IsiXhosa', family: 'Bantu' },
  yi: { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', family: 'Germanic' },
  yo: { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', family: 'Niger-Congo' },
  zu: { code: 'zu', name: 'Zulu', nativeName: 'IsiZulu', family: 'Bantu' },
  bm: { code: 'bm', name: 'Bambara', nativeName: 'Bamanankan', family: 'Mande' },
  sgn: { code: 'sgn', name: 'Sign Language', nativeName: 'Sign Language', family: 'Sign' },
  multi: { code: 'multi', name: 'Multilingual', nativeName: 'Multilingual' },
};

/**
 * Maps common language name variations, typos, and alternate forms to ISO codes.
 * All keys must be lowercase.
 */
export const LANGUAGE_ALIASES: Record<string, string> = {
  // English names
  afrikaans: 'af',
  amharic: 'am',
  arabic: 'ar',
  armenian: 'hy',
  azerbaijani: 'az',
  basque: 'eu',
  belarusian: 'be',
  bengali: 'bn',
  bosnian: 'bs',
  bulgarian: 'bg',
  burmese: 'my',
  cambodian: 'km',
  cantonese: 'yue',
  catalan: 'ca',
  chinese: 'zh',
  mandarin: 'zh',
  croatian: 'hr',
  czech: 'cs',
  danish: 'da',
  dutch: 'nl',
  english: 'en',
  estonian: 'et',
  finnish: 'fi',
  french: 'fr',
  fula: 'ff',
  fulani: 'ff',
  fulfulde: 'ff',
  georgian: 'ka',
  german: 'de',
  greek: 'el',
  gujarati: 'gu',
  hausa: 'ha',
  hebrew: 'he',
  hindi: 'hi',
  hungarian: 'hu',
  icelandic: 'is',
  igbo: 'ig',
  indonesian: 'id',
  irish: 'ga',
  italian: 'it',
  japanese: 'ja',
  javanese: 'jv',
  kannada: 'kn',
  kazakh: 'kk',
  khmer: 'km',
  kirundi: 'rn',
  kongo: 'kg',
  kikongo: 'kg',
  korean: 'ko',
  kurdish: 'ku',
  kyrgyz: 'ky',
  lao: 'lo',
  latin: 'la',
  latvian: 'lv',
  lingala: 'ln',
  lithuanian: 'lt',
  luganda: 'lg',
  luxembourgish: 'lb',
  macedonian: 'mk',
  malagasy: 'mg',
  malay: 'ms',
  malayalam: 'ml',
  maltese: 'mt',
  maori: 'mi',
  marathi: 'mr',
  mongolian: 'mn',
  nepali: 'ne',
  norwegian: 'no',
  chichewa: 'ny',
  chinyanja: 'ny',
  nyanja: 'ny',
  pashto: 'ps',
  persian: 'fa',
  farsi: 'fa',
  polish: 'pl',
  portuguese: 'pt',
  punjabi: 'pa',
  romanian: 'ro',
  russian: 'ru',
  samoan: 'sm',
  'scottish gaelic': 'gd',
  serbian: 'sr',
  'serbo-croatian': 'sh',
  shona: 'sn',
  sinhala: 'si',
  sinhalese: 'si',
  slovak: 'sk',
  slovene: 'sl',
  slovenian: 'sl',
  somali: 'so',
  spanish: 'es',
  swahili: 'sw',
  swedish: 'sv',
  tagalog: 'tl',
  filipino: 'tl',
  tamil: 'ta',
  telugu: 'te',
  thai: 'th',
  tigrinya: 'ti',
  turkish: 'tr',
  turkmen: 'tk',
  twi: 'tw',
  ukrainian: 'uk',
  urdu: 'ur',
  uzbek: 'uz',
  vietnamese: 'vi',
  welsh: 'cy',
  xhosa: 'xh',
  yiddish: 'yi',
  yoruba: 'yo',
  zulu: 'zu',
  bambara: 'bm',
  'sign language': 'sgn',
  multilingual: 'multi',

  // French names
  français: 'fr',
  francais: 'fr',
  anglais: 'en',
  espagnol: 'es',
  allemand: 'de',
  italien: 'it',
  portugais: 'pt',
  russe: 'ru',
  arabe: 'ar',
  chinois: 'zh',
  japonais: 'ja',
  coréen: 'ko',
  coreen: 'ko',
  turc: 'tr',
  polonais: 'pl',
  roumain: 'ro',
  néerlandais: 'nl',
  neerlandais: 'nl',
  suédois: 'sv',
  suedois: 'sv',
  norvégien: 'no',
  norvegien: 'no',
  danois: 'da',
  finnois: 'fi',
  grec: 'el',
  hongrois: 'hu',
  tchèque: 'cs',
  tcheque: 'cs',
  bulgare: 'bg',
  croate: 'hr',
  serbe: 'sr',
  hébreu: 'he',
  hebreu: 'he',
  persan: 'fa',
  thaï: 'th',
  vietnamien: 'vi',
  indonésien: 'id',
  indonesien: 'id',
  malais: 'ms',
  gallois: 'cy',
  irlandais: 'ga',
};

/**
 * Resolves a raw language value to a validated ISO code.
 * Accepts ISO codes, full language names (English/French), and common aliases.
 * Returns null if unresolvable.
 */
export function resolveLanguageCode(raw: string): string | null {
  if (!raw) return null;

  const normalized = raw.trim().toLowerCase();
  if (!normalized) return null;

  // Special case: "multi" / "multilingual"
  if (normalized === 'multi' || normalized === 'multilingual') return 'multi';

  // Direct ISO code match
  if (LANGUAGE_REGISTRY[normalized]) return normalized;

  // Alias lookup
  if (LANGUAGE_ALIASES[normalized]) return LANGUAGE_ALIASES[normalized];

  // If it looks like a valid 2-3 letter code but isn't in our registry,
  // return it as-is (graceful degradation for rare codes)
  if (/^[a-z]{2,3}$/.test(normalized)) return normalized;

  return null;
}

/**
 * Returns the display name for a language code.
 */
export function getLanguageDisplayName(code: string): string {
  return LANGUAGE_REGISTRY[code]?.name ?? code.toUpperCase();
}
